import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="h-dvh w-full bg-black text-white">
          
          {/* <div className="h-full w-full absolute flex items-center justify-center bg-white/5 backdrop-blur-xs">
            popUp
          </div> */}
          {children}</section>
      </body>
    </html>
  );
}
